a = int(input("Please Enter the first number: "))
b = int(input("Please Enter the second number: "))
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Quotient:", a / b)